---
- name: install packages
  with_items: "{{ jabber_packages }}"
  pkgng:
    name: "{{ item.name }}"
  notify:
    - restart ejabberd

- name: enable ejabberd service
  template:
    src: ejabberd.j2
    dest: /etc/rc.conf.d/ejabberd

- name: configure ejabber
  with_items: "{{ jabber_templates }}"
  template:
    src: "{{ item.filename }}.tpl"
    dest: "{{ item.destination }}/{{ item.filename }}"
  notify:
    - restart ejabberd
