---
- name: install packages
  with_items: "{{ jabber_packages }}"
  package:
    name: "{{ item.name }}"
  notify:
    - restart prosody

- name: enable prosody service
  template:
    src: prosody.j2
    dest: /etc/rc.conf.d/prosody

- name: install cert updater
  copy:
    src: update_certs.sh
    dest: /usr/local/bin/update_certs.sh
    mode: 0755

- name: convert cert from letsencrypt
  command: /usr/local/bin/update_certs.sh "{{ jabber_domain }}"
  args:
    creates: "/usr/local/etc/prosody/certs/{{ jabber_domain }}.key"

- name: create log and run dirs
  with_items:
    - log
    - run
  file:
    name: "/var/{{ item }}/prosody"
    mode: 0755
    owner: prosody
    group: prosody
    state: directory

- name: configure prosody
  template:
    src: prosody.cfg.lua.j2
    dest: /usr/local/etc/prosody/prosody.cfg.lua
  notify:
    - restart prosody
